/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main (void)
{
  GtkWidget *main;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *quit1;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *about1;
  GtkWidget *table2;
  GtkWidget *btnUp;
  GtkWidget *image3;
  GtkWidget *btnStop;
  GtkWidget *image1;
  GtkWidget *btnDown;
  GtkWidget *image2;
  GtkWidget *btnLeftDown;
  GtkWidget *image8;
  GtkWidget *btnRightDown;
  GtkWidget *image7;
  GtkWidget *btnLeft;
  GtkWidget *image5;
  GtkWidget *btnRight;
  GtkWidget *image4;
  GtkWidget *btnLeftUp;
  GtkWidget *image9;
  GtkWidget *btnRightUp;
  GtkWidget *image6;
  GtkWidget *btnFire;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main), _("Missile Launcher Interface"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about1);

  table2 = gtk_table_new (6, 4, FALSE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox1), table2, TRUE, TRUE, 0);

  btnUp = gtk_button_new ();
  gtk_widget_show (btnUp);
  gtk_table_attach (GTK_TABLE (table2), btnUp, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, btnUp, _("Up"), NULL);
  gtk_widget_add_accelerator (btnUp, "clicked", accel_group,
                              GDK_8, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnUp, "clicked", accel_group,
                              GDK_w, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnUp, "clicked", accel_group,
                              GDK_Up, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image3 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (btnUp), image3);

  btnStop = gtk_button_new ();
  gtk_widget_show (btnStop);
  gtk_table_attach (GTK_TABLE (table2), btnStop, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, btnStop, _("Stop"), NULL);
  gtk_widget_add_accelerator (btnStop, "clicked", accel_group,
                              GDK_5, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnStop, "clicked", accel_group,
                              GDK_s, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image1 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (btnStop), image1);

  btnDown = gtk_button_new ();
  gtk_widget_show (btnDown);
  gtk_table_attach (GTK_TABLE (table2), btnDown, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, btnDown, _("Down"), NULL);
  gtk_widget_add_accelerator (btnDown, "clicked", accel_group,
                              GDK_2, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnDown, "clicked", accel_group,
                              GDK_Down, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnDown, "clicked", accel_group,
                              GDK_x, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image2 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (btnDown), image2);

  btnLeftDown = gtk_button_new ();
  gtk_widget_show (btnLeftDown);
  gtk_table_attach (GTK_TABLE (table2), btnLeftDown, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_add_accelerator (btnLeftDown, "clicked", accel_group,
                              GDK_1, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnLeftDown, "clicked", accel_group,
                              GDK_z, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image8 = create_pixmap (main, "move-left-down.png");
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (btnLeftDown), image8);

  btnRightDown = gtk_button_new ();
  gtk_widget_show (btnRightDown);
  gtk_table_attach (GTK_TABLE (table2), btnRightDown, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_add_accelerator (btnRightDown, "clicked", accel_group,
                              GDK_3, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnRightDown, "clicked", accel_group,
                              GDK_c, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image7 = create_pixmap (main, "move-right-down.png");
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (btnRightDown), image7);

  btnLeft = gtk_button_new ();
  gtk_widget_show (btnLeft);
  gtk_table_attach (GTK_TABLE (table2), btnLeft, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, btnLeft, _("Left"), NULL);
  gtk_widget_add_accelerator (btnLeft, "clicked", accel_group,
                              GDK_4, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnLeft, "clicked", accel_group,
                              GDK_Left, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnLeft, "clicked", accel_group,
                              GDK_a, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_focus_on_click (GTK_BUTTON (btnLeft), FALSE);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (btnLeft), image5);

  btnRight = gtk_button_new ();
  gtk_widget_show (btnRight);
  gtk_table_attach (GTK_TABLE (table2), btnRight, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, btnRight, _("Right"), NULL);
  gtk_widget_add_accelerator (btnRight, "clicked", accel_group,
                              GDK_6, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnRight, "clicked", accel_group,
                              GDK_Right, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnRight, "clicked", accel_group,
                              GDK_d, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image4 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (btnRight), image4);

  btnLeftUp = gtk_button_new ();
  gtk_widget_show (btnLeftUp);
  gtk_table_attach (GTK_TABLE (table2), btnLeftUp, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_add_accelerator (btnLeftUp, "clicked", accel_group,
                              GDK_7, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnLeftUp, "clicked", accel_group,
                              GDK_q, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image9 = create_pixmap (main, "move-left-up.png");
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (btnLeftUp), image9);

  btnRightUp = gtk_button_new ();
  gtk_widget_show (btnRightUp);
  gtk_table_attach (GTK_TABLE (table2), btnRightUp, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_add_accelerator (btnRightUp, "clicked", accel_group,
                              GDK_9, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btnRightUp, "clicked", accel_group,
                              GDK_e, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  image6 = create_pixmap (main, "move-right-up.png");
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (btnRightUp), image6);

  btnFire = gtk_button_new_with_mnemonic (_("Fire!"));
  gtk_widget_show (btnFire);
  gtk_table_attach (GTK_TABLE (table2), btnFire, 0, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_add_accelerator (btnFire, "clicked", accel_group,
                              GDK_space, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_table_attach (GTK_TABLE (table2), statusbar1, 0, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  g_signal_connect ((gpointer) main, "show",
                    G_CALLBACK (on_main_show),
                    NULL);
  g_signal_connect ((gpointer) main, "destroy",
                    G_CALLBACK (on_main_destroy),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) btnUp, "clicked",
                    G_CALLBACK (on_btnUp_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnStop, "clicked",
                    G_CALLBACK (on_btnStop_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnStop, "clicked",
                    G_CALLBACK (on_btnStop_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnDown, "clicked",
                    G_CALLBACK (on_btnDown_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnLeftDown, "clicked",
                    G_CALLBACK (on_btnLeftDown_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnRightDown, "clicked",
                    G_CALLBACK (on_btnRightDown_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnLeft, "clicked",
                    G_CALLBACK (on_btnLeft_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnRight, "clicked",
                    G_CALLBACK (on_btnRight_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnLeftUp, "clicked",
                    G_CALLBACK (on_btnLeftUp_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnRightUp, "clicked",
                    G_CALLBACK (on_btnRightUp_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnFire, "clicked",
                    G_CALLBACK (on_btnFire_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main, main, "main");
  GLADE_HOOKUP_OBJECT (main, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (main, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (main, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (main, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (main, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (main, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (main, about1, "about1");
  GLADE_HOOKUP_OBJECT (main, table2, "table2");
  GLADE_HOOKUP_OBJECT (main, btnUp, "btnUp");
  GLADE_HOOKUP_OBJECT (main, image3, "image3");
  GLADE_HOOKUP_OBJECT (main, btnStop, "btnStop");
  GLADE_HOOKUP_OBJECT (main, image1, "image1");
  GLADE_HOOKUP_OBJECT (main, btnDown, "btnDown");
  GLADE_HOOKUP_OBJECT (main, image2, "image2");
  GLADE_HOOKUP_OBJECT (main, btnLeftDown, "btnLeftDown");
  GLADE_HOOKUP_OBJECT (main, image8, "image8");
  GLADE_HOOKUP_OBJECT (main, btnRightDown, "btnRightDown");
  GLADE_HOOKUP_OBJECT (main, image7, "image7");
  GLADE_HOOKUP_OBJECT (main, btnLeft, "btnLeft");
  GLADE_HOOKUP_OBJECT (main, image5, "image5");
  GLADE_HOOKUP_OBJECT (main, btnRight, "btnRight");
  GLADE_HOOKUP_OBJECT (main, image4, "image4");
  GLADE_HOOKUP_OBJECT (main, btnLeftUp, "btnLeftUp");
  GLADE_HOOKUP_OBJECT (main, image9, "image9");
  GLADE_HOOKUP_OBJECT (main, btnRightUp, "btnRightUp");
  GLADE_HOOKUP_OBJECT (main, image6, "image6");
  GLADE_HOOKUP_OBJECT (main, btnFire, "btnFire");
  GLADE_HOOKUP_OBJECT (main, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT_NO_REF (main, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (main), accel_group);

  return main;
}

GtkWidget*
create_about (void)
{
  GtkWidget *about;
  GtkWidget *dialog_vbox1;
  GtkWidget *aboutImage;
  GtkWidget *label1;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  about = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (about), _("About MissileLauncher"));
  gtk_window_set_type_hint (GTK_WINDOW (about), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (about)->vbox;
  gtk_widget_show (dialog_vbox1);

  aboutImage = gtk_image_new_from_icon_name ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (aboutImage);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), aboutImage, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("<b>Missile Launcher 1.0</b>\n\nMissile Launcher is an application\nto control a USB Missile Launcher\nFor GTK+ and Gnome.  It is written\nusing libusb.\n\n<i>(C) 2006-2008 Chris Boersma</i>"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label1, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_CENTER);

  dialog_action_area1 = GTK_DIALOG (about)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (about), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (okbutton1, "clicked", accel_group,
                              GDK_o, (GdkModifierType) GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about, about, "about");
  GLADE_HOOKUP_OBJECT_NO_REF (about, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (about, aboutImage, "aboutImage");
  GLADE_HOOKUP_OBJECT (about, label1, "label1");
  GLADE_HOOKUP_OBJECT_NO_REF (about, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (about, okbutton1, "okbutton1");

  gtk_window_add_accel_group (GTK_WINDOW (about), accel_group);

  return about;
}

